//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WineRater.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WineRater.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AppBarAddText {
            get {
                return ResourceManager.GetString("AppBarAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AppBarCancelText {
            get {
                return ResourceManager.GetString("AppBarCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AppBarDeleteText {
            get {
                return ResourceManager.GetString("AppBarDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string AppBarEditText {
            get {
                return ResourceManager.GetString("AppBarEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AppBarSaveText {
            get {
                return ResourceManager.GetString("AppBarSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINE RATER.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete?.
        /// </summary>
        public static string DetailsPageDeleteText {
            get {
                return ResourceManager.GetString("DetailsPageDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion.
        /// </summary>
        public static string DetailsPageDeleteTitle {
            get {
                return ResourceManager.GetString("DetailsPageDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of wines.
        /// </summary>
        public static string MainPageListOfWines {
            get {
                return ResourceManager.GetString("MainPageListOfWines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SaveWinePageName {
            get {
                return ResourceManager.GetString("SaveWinePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string SaveWinePageRating {
            get {
                return ResourceManager.GetString("SaveWinePageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        public static string SaveWinePageTakeAPicture {
            get {
                return ResourceManager.GetString("SaveWinePageTakeAPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a wine.
        /// </summary>
        public static string SaveWinePageTitle {
            get {
                return ResourceManager.GetString("SaveWinePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SaveWinePageType {
            get {
                return ResourceManager.GetString("SaveWinePageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortified.
        /// </summary>
        public static string WineTypeFortified {
            get {
                return ResourceManager.GetString("WineTypeFortified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string WineTypeRed {
            get {
                return ResourceManager.GetString("WineTypeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosé.
        /// </summary>
        public static string WineTypeRose {
            get {
                return ResourceManager.GetString("WineTypeRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sparkling.
        /// </summary>
        public static string WineTypeSparkling {
            get {
                return ResourceManager.GetString("WineTypeSparkling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string WineTypeUnknown {
            get {
                return ResourceManager.GetString("WineTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string WineTypeWhite {
            get {
                return ResourceManager.GetString("WineTypeWhite", resourceCulture);
            }
        }
    }
}
